// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiredBrainCoffee.Api;

#nullable disable

namespace WiredBrainCoffee.Api.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20220515105221_CreateOrderItem")]
    partial class CreateOrderItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("WiredBrainCoffee.Models.Extras", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Creamer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flavor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Milk")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topping")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("WiredBrainCoffee.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromoCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 5, 15, 11, 52, 21, 19, DateTimeKind.Local).AddTicks(1470),
                            Description = "A coffee order",
                            OrderNumber = 100,
                            PromoCode = "Wired123",
                            Total = 25m
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 5, 15, 11, 52, 21, 19, DateTimeKind.Local).AddTicks(2100),
                            Description = "A food order",
                            OrderNumber = 125,
                            PromoCode = "Wired123",
                            Total = 35m
                        });
                });

            modelBuilder.Entity("WiredBrainCoffee.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Extrasid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Extrasid");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WiredBrainCoffee.Models.OrderItem", b =>
                {
                    b.HasOne("WiredBrainCoffee.Models.Extras", "Extras")
                        .WithMany()
                        .HasForeignKey("Extrasid");

                    b.HasOne("WiredBrainCoffee.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.Navigation("Extras");
                });

            modelBuilder.Entity("WiredBrainCoffee.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
